### ISSUE TITLE
weewx 4, Python 3 and weewx-realtime_clientraw

### ISSUE THREAD

**Issue by u2kdd** [gjr80/weewx-realtime_clientraw#3]
Hi Gary

Ihave updated weewx and python and after that I have found some issues in rtcr.py. I think they are now solved but I have another issue. It would be nice if you can help me again.

BR from Dresden
Ulf
[issue.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/4740118/issue.txt)

**Comment by gjr80** [comment]
Hi Ulf,

I will have a look, is there anything else in the log? If not could you provide me with a `debug = 1` log output that includes the WeeWX startup sequence. That is the easiest way for me to get all your important config details.

**Comment by u2kdd** [comment]
Hi Gary
Attached you will find the requested logfile and furthermore a file "issues hopefully solved". In the second file I have listed the issues and my modification in rtcr.py.

I hope it will be helpful for you.
[logfile.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/4741634/logfile.txt)

[issues hopefully solved.txt](https://github.com/gjr80/weewx-realtime_clientraw/files/4741635/issues.hopefully.solved.txt)

BR Ulf

**Comment by gjr80** [comment]
Thanks Ulf, I thought I had largely cut over rctr to WeeWX 4/python 3 but it seems I have not. I will see if I can get this tidied up this week.

Gary

**Comment by u2kdd** [comment]
I am sure you will get it. I hope the tips I have got from Google are not completely wrong.
Many thanks in advance!

Ulf

**Comment by gjr80** [comment]
OK Ulf I have an updated `rtctr.py` for you to try. 

You were on the right track with your changes though they were python3 specific and I am trying to keep all of my code python2 and python3 compatible. This way the code can be run under WeeWX 3 and 4, though WeeWX 3/4 compatibility introduces a number of other challenges (different logging mechanisms for one). But I digress. The revised `rtcr.py` should work under WeeWX 3.4+ or 4.x using python 2.7 or python 3.x.

To use the new `rtcr.py`:
1. move aside your existing `rtcr.py`:
```
$ mv /usr/share/weewx/user/rtcr.py /usr/share/weewx/user/rtcr_orig.py
```
2. download the new `rtcr.py` in place of your old:
```
$ wget -P /usr/share/weewx/user https://raw.githubusercontent.com/gjr80/weewx-realtime_clientraw/python3/bin/user/rtcr.py
```
3. restart WeeWX
4. monitor the log for errors

If you do have any problems could you set `debug = 1` and restart WeeWX and post a log extract from startup through until the error happens.

Gary

**Comment by u2kdd** [comment]
Hi Gary
I have seen your mail at 05:00 a.m but I had no time to check it this morning. Now after work I have checked it and it works very well.
Again many thanks for your fast support. 

BR Ulf
