### ISSUE TITLE
Error while collecting weather from Clientraw file data in weatherstation (wordpress)

### ISSUE THREAD

**Issue by u2kdd** [gjr80/weewx-realtime_clientraw#7]
Once again I need support ...

Clientraw came from weewx to the server as it should be. Since 05:30 this morning I get no new data on my homepage and I have found the below mentioned error in the log file from weather station in wordpress round about every 5 minutes. I have not made modifications within the last days.

example of the log entry:
Zeitstempel : 2021-03-09 20:01:48 (vor 44 Sekunden)
System : Weather Collector 3.8.10
Dienst : File Handler - Clientraw

Station : Dresden Ortsteil Altfranken (yx:00:00:00:00:02)
Modul : N/A (00:00:00:00:00:00)Error while collecting weather from Clientraw file data

I hope, that I am not alone with this problem.

BR
Ulf from Dresden

**Comment by hilman2** [comment]
Thats not a problem with clientraw.txt.

Weatherstation updated to 3.8.10 - it stopped working after the update

**Comment by u2kdd** [comment]
Hello hilman2

Many thanks for your answer. Have you an idea how long it will take to solve the problem? If possible please let me know what`s to do to roll back to the former version without losses of data.

BR Ulf from Dresden

**Comment by gjr80** [comment]
In my experience issues arise from time to time with the likes of clientraw.txt as it is a rigidly formatted file with little nothing by way of specifications other than some general descriptions. I will be the first to say there could well be an issue with realtime_clientraw, am happy to look into realtime_clientraw if anyone can provide some definitive error information.

Closing this for now but it can be re-opened if required.
